### ISSUE TITLE
Bug: `:g/^/m0` doesn't reverse lines 

### ISSUE THREAD

**Issue by tmalsburg** [emacs-evil/evil#1595]
# Issue type:
- Bug report

# Environment

Emacs version: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0) of 2022-04-07

Operating System: Ubuntu 21.10 
Evil version: Evil version 1.14.0
Evil installation type: straight.el
Graphical/Terminal: X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Enter some lines.  I tested with the example below.
- `g/^/m0`

```
- 3
- 2
- 1
```

# Expected behavior
Lines in buffer should be reversed.

# Actual behavior
Order of lines is changed but not reversed. Order seems to depend on position of cursor (not sure).

# Further notes
None.

**Comment by tomdl89** [comment]
```
20     0
19     1
18     2
17     3
16     4
15     5
14     6
13     7
12     8
11     9
10     10
9      11
8      12
7      13
6      14
5      15
4      16
3      17
2      18
1      20 <--
0      19 <--

```
something about the behaviour of g on the first/second line in a range 😕

**Comment by tomdl89** [comment]
@tmalsburg this should now be fixed in master. It turns out that `evil-move` was corrupting the markers list that `evil-ex-global` traverses through. I didn't have time to fully understand why, but the fix works in my testing. Lemme know if you notice any other weirdness around here.

**Comment by tmalsburg** [comment]
Just tested it and in the original scenario the problem seems to be solved.  However, there is a variation that still doesn't work: With the original test case
```
-3
-2
-1
```

then select all three lines in visual mode and `:'<,'>g/^/m0`.  This results in

```

-2
-1
-3

```

Note the empty lines at the top and bottom.  So after the command we have one additional line.  However, I get this incorrect result only when the point is on the last line when I execute the command.

**Comment by tomdl89** [comment]
Well spotted! I'll take a look when I get a chance.

**Comment by tomdl89** [comment]
@tmalsburg the visual selection case should now be fixed in master

**Comment by tmalsburg** [comment]
There is one corner case in which the current solution still deviates from vim (but perhaps that's too small to matter):  When the last line of the buffer doesn't end in newline, the last line after reordering will end with a newline, so an additional newline character is introduced.  Vim doesn't do this.  Other than that it seems to work as intended.  Thank you.

**Comment by tomdl89** [comment]
@tmalsburg - thanks for spotting. I'll take a look 🙏

**Comment by tmalsburg** [comment]
The last commit solved it.  Can't find any more issues :)  Thank you so much, Tom!
